### PR TITLE
Add Helm chart support

### PR DESCRIPTION
**Pull request by victorgetz**
Hi i think you need a helm chart :)
This one should do it

### CODE REVIEW

**Comment by SantiEich** [comment]
Amazing, thanks!

**Comment by victorgetz** [comment]
For sure you will need also helm lint and all the other CI stuff but i would make for that a additional pull request since i don't know if you are interested or not

**Comment by yahel2410** [comment]
Hey, do you plan to merge this one? We would be interested to try imagepullsecret-patcher and helm chart is highly preferred

**Comment by victorgetz** [comment]
Hi i created also a pipeline for a github pages helm chart repo so everyone can just do this:

```bash
$ helm repo add titansoft-pte-ltd titansoft-pte-ltd/imagepullsecret-patcher
$ helm search repo titansoft-pte-ltd
$ helm install -n imagepullsecret-patcher --create-namespace imagepullsecret-patcher titansoft-pte-ltd/imagepullsecret-patcher --set dockerConfigJsonBase64Encoded="REPLACE_ME"
```
You just need to create a "gh-pages" branch in your repository.

I also created a test pipeline for the helm chart.

**Comment by victorgetz** [comment]
ping owner @billjh yes? no?

**Comment by Morriz** [comment]
Darn, I just created one myself too ;p Should have looked at the issues list before hacking away. Took me an hour tho.

Anyway, I have a simplification to add to avoid the steps to create the pullsecret in the first place:

```
{{/*
Create the docker pull secret from the creds
*/}}
{{- define "dockercfg" -}}
{"auths":{"{{ .server | default "docker.io" }}":{"username":"{{ .username }}","password":"{{ .password | replace "\"" "\\\"" }}","email":"{{ .email | default "not@us.ed" }}","auth":"{{ print .username ":" .password | b64enc}}"}}}
{{- end -}}

```

**Comment by victorgetz** [comment]
I will close the Pull request since imagepullsecret-patcher does not really solve the problem. If the container is started before the patch happens then there is still a imagepullbackoff.

i went with a docker mirror proxy (harbor) + kubernetes crds webhook

**Comment by Morriz** [comment]
> I will close the Pull request since imagepullsecret-patcher does not really solve the problem. If the container is started before the patch happens then there is still a imagepullbackoff.
> 

I also have some issues with the solution here, but your reason is not valid imo, as k8s reconciles repeatedly back-offishly.

> i went with a docker mirror proxy (harbor) + kubernetes crds webhook

Pull through proxy like harbor is what we are also configuring, with many benefits. We have a nice stack integrated in redkubes/otomi now. Harbor preconfigured already but not yet as fully automated pull through proxy.

**Pull request closed without merging**
